function [ Xdot ] = robotSS( t, X, Xin, A, B, kGains, D )
%Let's make our state space model.  

%  B = [ 0 0 0 0 0 0;...
%        mT*cos(fA)/m mT*cos(fA)/m -mT*cos(aA)/m -mT*cos(aA)/m 0 0;...
%        0 0 0 0 0 0;...
%        mT*sin(fA)/m -mT*sin(fA)/m -mT*sin(aA)/m mT*sin(aA)/m mT*sin(zA)/m -mT*sin(zA)/m;...
%        0 0 0 0 0 0;...
%        0 0 0 0 -mT*cos(zA)/m -mT*cos(zA)/m;...
%        0 0 0 0 0 0;...
%        mT*tD*cos(tA)/In -mT*tD*cos(tA)/In mT*tD/In -mT*tD/In 0 0;...
%        0 0 0 0 0 0;...
%        0 0 0 0 -mT*tD/In mT*tD/In];
   % u = [0;0;0;0;0;0];
   
   Xdot = A*X-B*kGains*(X-Xin)+D;
   
end

